version: "2"
checks:
  similar-code:
    enabled: true
    config:
      threshold: 4 #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
